export const ACCOUNT_MODULE = 'CUSTOMER';
export enum ACCOUNT_ACTION {

  /*
    PROFILE RELATED
  */
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  /*
    ORDER RELATED
  */
  CREATE_ORDER = 'CREATE_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',

  DELETE_FILE = 'DELETE_FILE',
  SET_PASSWORD = 'SET_PASSWORD',
  EXPORT_ORDER = 'EXPORT_ORDER',
  EXPORT_REPORT = 'EXPORT_REPORT',

  /*
    ADDRESS RELATED
  */
  CREATE_ADDRESS = 'CREATE_ADDRESS',
  UPDATE_ADDRESS = 'UPDATE_ADDRESS',
  DELETE_ADDRESS = 'DELETE_ADDRESS',
  UPDATE_DEFAULT_REF = 'UPDATE_DEFAULT_REF',
}
