export enum TOKEN_TYPE {
  LOGIN = 'LOGIN_TOKEN',
  ADMIN_LOGIN = 'ADMIN_LOGIN_TOKEN',
  USER_LOGIN = 'USER_LOGIN_TOKEN',
  REGISTER = 'REGISTER_TOKEN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD_TOKEN',
  CHANGE_EMAIL = 'CHANGE_EMAIL_TOKEN',
  RESET_PASSWORD = 'RESET_PASSWORD',
  SET_PASSWORD = 'SET_PASSWORD',

  VERIFY = 'VERIFY',
}
